title: Lia Dougherty
logo: assets/Untitled design.png
description: am Lia Dougherty, a researcher and data enthusiast with a passion for applying quantitative methods to understand complex social and economic phenomena.
#show_downloads: true
theme: jekyll-theme-minimal
