title: "Lia Dougherty"
logo: "assets/Lia-Dougherty_square.webp"
description: >
  Data enthusiast with 1+ year of experience in capital markets and financial services, with a strong focus on data analysis, reporting, and process optimization.
theme: jekyll-theme-minimal
