title: Lia Dougherty
logo: /assets/1746336131358.jpg
description: I'm a recent Davidson College alumna, passionate about investigating socioeconomic phenomena through econometric and data-driven methods. I developed strong skills in econometrics, statistical analysis, NLP tools, text-based and sentiment-based research.
show_downloads: true
theme: jekyll-theme-minimal
