title: Lia Dougherty
logo: assets/Untitled design.png
description: I am Lia Dougherty, a researcher and data enthusiast with a passion<br>
for applying quantitative methods to understand complex social and economic phenomena.
theme: jekyll-theme-minimal
