title: "Lia Dougherty"
logo: "assets/Untitled design.png"
description: >
  Data enthusiast with a passion for applying quantitative methods to understand complex socioeconomic phenomena.
theme: jekyll-theme-minimal
<br>
