title: "Lia Dougherty"
logo: "assets/profile_pic_edited.png"
description: >
  Data enthusiast with 1+ year of experience in capital markets and financial services, with a strong focus on data analysis, reporting, and process optimization.
theme: jekyll-theme-minimal
