title: "Lia Dougherty"
logo: "assets/Untitled design.png"
description: >
  Data enthusiast with a passion for applying quantitative methods to understand socioeconomic phenomena
theme: jekyll-theme-minimal
